# Generated by Django 3.2.8 on 2021-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_service',
            field=models.ManyToManyField(through='articles.Combination', to='articles.Service'),
        ),
    ]
