# Generated by Django 3.2.8 on 2021-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.IntegerField(default=0)),
                ('customerFirstName', models.CharField(max_length=30)),
                ('customerLastName', models.CharField(max_length=30)),
                ('customerService', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField(default=0)),
                ('employeeFirstName', models.CharField(max_length=30)),
                ('employeeLastName', models.CharField(max_length=30)),
                ('employeeAllowedAccess', models.BooleanField(default=False)),
                ('employeePosition', models.CharField(max_length=30)),
                ('employeeSalary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.IntegerField(default=0)),
                ('serviceName', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Articale',
        ),
    ]
