# Generated by Django 3.2.8 on 2021-10-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211030_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerService',
            new_name='customerServiceLevel',
        ),
        migrations.AddField(
            model_name='service',
            name='serviceLevel',
            field=models.IntegerField(default=0),
        ),
    ]
