# Generated by Django 3.2.8 on 2021-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211031_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='editUpdateCustomerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.IntegerField(default=0)),
                ('customerFirstName', models.CharField(max_length=30)),
                ('customerLastName', models.CharField(max_length=100)),
                ('customerServicelevel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CustomerList',
            },
        ),
    ]
