# Generated by Django 3.2.8 on 2021-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_editupdatecustomerrecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cregistration',
        ),
        migrations.DeleteModel(
            name='editUpdateCustomerRecords',
        ),
        migrations.DeleteModel(
            name='eregistration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceID',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerServiceLevel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeSalary',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceLevel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='articles_customer',
        ),
    ]
