# Generated by Django 3.2.8 on 2021-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20211031_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerServiceLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeSalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceLevel',
            field=models.IntegerField(default=0),
        ),
    ]
