# Generated by Django 3.2.8 on 2021-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20211031_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serviceLevel',
        ),
        migrations.AddField(
            model_name='service',
            name='serviceLevel',
            field=models.ManyToManyField(related_name='Services', to='articles.Customer'),
        ),
    ]
