# Generated by Django 3.2.8 on 2021-11-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_employees_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerFirstName',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerLastName',
            new_name='customer_last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerServiceLevel',
            new_name='customer_service_level',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeAllowedAccess',
            new_name='employee_allowed_access',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeFirstName',
            new_name='employee_first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeLastName',
            new_name='employee_last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeePosition',
            new_name='employee_position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeSalary',
            new_name='employee_salary',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceLevel',
            new_name='service_level',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceName',
            new_name='service_name',
        ),
    ]
