# Generated by Django 3.2.8 on 2021-11-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20211103_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_level',
        ),
        migrations.AddField(
            model_name='service',
            name='service_level',
            field=models.IntegerField(default=0),
        ),
    ]
