# Generated by Django 3.2.8 on 2021-11-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20211103_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_level',
            new_name='service_customer_id',
        ),
    ]
