# Generated by Django 3.2.8 on 2021-11-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rename_service_level_service_service_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_customer_id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_customers',
            field=models.ManyToManyField(related_name='Services', to='articles.Customer'),
        ),
    ]
