# Generated by Django 3.2.8 on 2021-11-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20211104_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_service_level',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_service',
            field=models.ManyToManyField(to='articles.Service'),
        ),
    ]
